FinalSeminar/OnlineGallery/Models/Product.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineGallery.Models
{
    [Table("Product")]
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("Id", TypeName = "int")]
        public int Id { get; set; }

        [Required(ErrorMessage = "- Enter product name")]
        [Column("Name", TypeName = "nvarchar(50)")]
        public string Name { get; set; }

        [Column("Image", TypeName = "nvarchar(450)")]
        public string Image { get; set; }
        [NotMapped]
        public IFormFile FileImage { get; set; }

        [DisplayName("Default Price")]
        [Required(ErrorMessage = "- Invalid price")]
        [Range(1, double.MaxValue, ErrorMessage = "- Price must greater than 0")]
        [Column("DefaultPrice", TypeName = "int")]
        public int? DefaultPrice { get; set; }

        [Required(ErrorMessage = "- Choose condition")]
        [Column("Condition", TypeName = "nvarchar(50)")]
        public string Condition { get; set; }

        [Required(ErrorMessage = "- Invalid year of manufacture")]
        [Range(1900, 2021, ErrorMessage = "- The year must be between 1900-2021")]
        [Column("Year", TypeName = "int")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "- Fill the fuel text")]
        [Column("Fuel", TypeName = "nvarchar(50)")]
        public string Fuel { get; set; }

        [Required(ErrorMessage = "- Please select hoose color.")]
        [Column("Color", TypeName = "nvarchar(50)")]
        public string Color { get; set; }

        [DisplayName("Mileage (miles)")]
        [Required(ErrorMessage = "- Mileage can not be null.")]
        [Range(1, double.MaxValue, ErrorMessage = "- Mileage must greater than 0")]
        [Column("Mileage", TypeName = "int")]
        public int? Mileage { get; set; }

        [Required(ErrorMessage = "- Enter the engine type.")]
        [Column("Engine", TypeName = "nvarchar(50)")]
        public string Engine { get; set; }

        [Required(ErrorMessage = "- Please select transmission.")]
        [Column("Transmission", TypeName = "nvarchar(50)")]
        public string Transmission { get; set; }

        [Required(ErrorMessage = "- Please set the number of doors")]
        [Range(1, int.MaxValue, ErrorMessage = "- The car must have at least 1 door")]
        [Column("Doors", TypeName = "int")]
        public int? Doors { get; set; }

        [Column("Description", TypeName = "nvarchar(MAX)")]
        public string Description { get; set; }

        [Column("Status", TypeName = "bit")]
        public bool Status { get; set; }

        public Auction Auction { get; set; }
    }
}

FinalSeminar/OnlineGallery/Controllers/AuctionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineGallery.Data;
using OnlineGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineGallery.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AuctionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AuctionController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Auction/List
        public async Task<IActionResult> Index()
        {
            return View(await _context.Auctions.ToListAsync());
        }

        // GET: Auction/CreateOrUpdate
        // GET: Auction/CreateOrUpdate/5
        [NoDirectAccess]
        public async Task<IActionResult> CreateOrUpdate(int id = 0)
        {
            if (id == 0)
            {
                return base.View(new Auction());
            }
            else
            {
                await _context.Products.ToListAsync();
                var auction = await _context.Auctions.FindAsync(id);
                if (auction == null)
                {
                    return NotFound();
                }
                return View(auction);
            }
        }

        // GET: Auction/CreateAuction/5
        [NoDirectAccess]
        public async Task<IActionResult> CreateAuction(int id)
        {
            var product = await _context.Products.FindAsync(id);
            return View(new Auction() { ProductId = id, Product = product });
        }

        // POST: Auction/CreateOrUpdate/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrUpdate(int id, Auction auction)
        {
            if (auction.StartDay.Value.CompareTo(DateTime.Now) < 0)
            {
                ModelState.AddModelError("DateError", "- The starting day cannot be earlier than today.");
            }
            else if (auction.StartDay.Value.CompareTo(auction.ClosingDay.Value) >= 0)
            {
                ModelState.AddModelError("DateError", "- The starting day cannot be greater or the same day as the closing day.");
            }
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    _context.Add(auction);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    try
                    {
                        _context.Update(auction);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!AuctionExists(auction.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewString(this, "_ViewAll", _context.Auctions.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewString(this, "CreateOrUpdate", auction) });
        }

        // POST: Auction/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var auction = await _context.Auctions.FindAsync(id);
            _context.Remove(auction);
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewString(this, "_ViewAll", _context.Auctions.ToList()) });
        }

        private bool AuctionExists(int id)
        {
            return _context.Auctions.Any(e => e.Id == id);
        }
    }
}

FinalSeminar/OnlineGallery/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineGallery.Data;
using OnlineGallery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace OnlineGallery.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            await _context.Auctions.ToListAsync();
            return View(await _context.Products.ToListAsync());
        }

        // GET: Product/CreateOrUpdate
        // GET: Product/CreateOrUpdate/5
        [NoDirectAccess]
        public async Task<IActionResult> CreateOrUpdate(int id = 0)
        {
            if (id == 0)
            {
                return base.View(new Product());
            }
            else
            {
                var product = await _context.Products.FindAsync(id);
                if (product == null)
                {
                    return NotFound();
                }
                return View(product);
            }
        }

        // POST: Product/CreateOrUpdate/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrUpdate(int id, Product product)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    if (product.FileImage != null)
                    {
                        product.Image = Tools.SaveImage(_webHostEnvironment, product.FileImage);
                    }
                    _context.Add(product);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    try
                    {
                        if (product.FileImage != null)
                        {
                            Tools.RemoveImage(_webHostEnvironment, product.Image);
                            product.Image = Tools.SaveImage(_webHostEnvironment, product.FileImage);
                        }
                        _context.Update(product);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductExists(product.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewString(this, "_ViewAll", _context.Products.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewString(this, "CreateOrUpdate", product) });
        }

        // GET: Product/AddImage
        // GET: Product/AddImage/5
        [NoDirectAccess]
        public async Task<IActionResult> AddImage(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Product/Sold/5
        //[HttpPost, ActionName("Sold")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> SoldConfirmed(int id)
        //{
        //    var product = await _context.Products.FindAsync(id);
        //    product.Status = false;
        //    _context.Update(product);
        //    await _context.SaveChangesAsync();
        //    return Json(new { html = Helper.RenderRazorViewString(this, "_ViewAll", _context.Products.ToList()) });
        //}

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

FinalSeminar/OnlineGallery/Controllers/ProductImageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineGallery.Data;
using OnlineGallery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineGallery.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductImageController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductImageController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            await _context.Products.ToListAsync();
            return View(await _context.ProductImages.ToListAsync());
        }

        // GET: Product/CreateOrUpdate
        // GET: Product/CreateOrUpdate/5
        [NoDirectAccess]
        public async Task<IActionResult> CreateOrUpdate(int id = 0)
        {
            await _context.Products.ToListAsync();
            if (id == 0)
            {
                return base.View(new ProductImage());
            }
            else
            {
                var productImage = await _context.ProductImages.FindAsync(id);
                if (productImage == null)
                {
                    return NotFound();
                }
                return View(productImage);
            }
        }

        // GET: Product/AddGallery/5
        [NoDirectAccess]
        public async Task<IActionResult> AddGallery(int id)
        {
            var product = await _context.Products.FindAsync(id);
            return View(new ProductImage() { ProductId = id, Product = product });
        }

        // POST: Product/CreateOrUpdate/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrUpdate(int id, ProductImage productImage)
        {
            if (id == 0 && productImage.FileImage == null)
            {
                ModelState.AddModelError("Image", "- Please choose at least 1 image.");
            }
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    foreach (var image in productImage.FileImage)
                    {
                        ProductImage item = new() { ProductId = productImage.ProductId, Image = Tools.SaveImage(_webHostEnvironment, image) };
                        _context.Add(item);
                        await _context.SaveChangesAsync();
                    }
                    var product = await _context.Products.FindAsync(productImage.ProductId);
                    var soldProduct = await _context.TransactionDetails.Select(e => e.Product).ToListAsync();
                    if (!soldProduct.Contains(product))
                    {
                        product.Status = true;
                        await _context.SaveChangesAsync();
                    }
                }
                else
                {
                    try
                    {
                        if (productImage.FileImage != null)
                        {
                            Tools.RemoveImage(_webHostEnvironment, productImage.Image);
                            productImage.Image = Tools.SaveImage(_webHostEnvironment, productImage.FileImage[0]);
                        }
                        _context.Update(productImage);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductImageExists(productImage.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewString(this, "_ViewAll", _context.ProductImages.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewString(this, "CreateOrUpdate", productImage) });
        }

        // POST: ProductImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productImage = await _context.ProductImages.FindAsync(id);
            var productId = productImage.ProductId;
            Tools.RemoveImage(_webHostEnvironment, productImage.Image);
            _context.Remove(productImage);
            await _context.SaveChangesAsync();
            if (!Tools.CheckGalleryProduct(_context, productId.Value))
            {
                var product = await _context.Products.FindAsync(productId);
                product.Status = false;
                _context.Update(product);
                await _context.SaveChangesAsync();
            }
            return Json(new { html = Helper.RenderRazorViewString(this, "_ViewAll", _context.ProductImages.ToList()) });
        }

        private bool ProductImageExists(int id)
        {
            return _context.ProductImages.Any(e => e.Id == id);
        }
    }
}

FinalSeminar/OnlineGallery/Views/Product/AddImage.cshtml
@model OnlineGallery.Models.Product

@{
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <ul class="font-weight-bolder" style="list-style: none;">
            <li><span asp-validation-for="Name" class="text-danger"></span></li>
            <li><span asp-validation-for="Status" class="text-danger"></span></li>
            <li><span asp-validation-for="Transmission" class="text-danger"></span></li>
            <li><span asp-validation-for="FileImage" class="text-danger"></span></li>
            <li><span asp-validation-for="Year" class="text-danger"></span></li>
            <li><span asp-validation-for="Condition" class="text-danger"></span></li>
            <li><span asp-validation-for="DefaultPrice" class="text-danger"></span></li>
            <li><span asp-validation-for="Color" class="text-danger"></span></li>
            <li><span asp-validation-for="Fuel" class="text-danger"></span></li>
            <li><span asp-validation-for="Engine" class="text-danger"></span></li>
            <li><span asp-validation-for="Mileage" class="text-danger"></span></li>
            <li><span asp-validation-for="Doors" class="text-danger"></span></li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form asp-action="CreateOrUpdate" enctype="multipart/form-data" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" value="@Model.Id" />
            <input type="hidden" asp-for="Name" value="@Model.Name" />
            <input type="hidden" asp-for="DefaultPrice" value="@Model.DefaultPrice" />
            <input type="hidden" asp-for="Condition" value="@Model.Condition" />
            <input type="hidden" asp-for="Year" value="@Model.Year" />
            <input type="hidden" asp-for="Fuel" value="@Model.Fuel" />
            <input type="hidden" asp-for="Color" value="@Model.Color" />
            <input type="hidden" asp-for="Mileage" value="@Model.Mileage" />
            <input type="hidden" asp-for="Engine" value="@Model.Engine" />
            <input type="hidden" asp-for="Transmission" value="@Model.Transmission" />
            <input type="hidden" asp-for="Doors" value="@Model.Doors" />
            <input type="hidden" asp-for="Description" value="@Model.Description" />
            <input type="hidden" asp-for="Status" value="@Model.Status" />
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label asp-for="Image" class="control-label"></label>
                        <input asp-for="FileImage" class="form-control" accept="image/*" />
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-12">
                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    DecoupledEditor
        .create(document.querySelector('#editor'))
        .then(editor => {
            const toolbarContainer = document.querySelector('#toolbar-container');

            toolbarContainer.appendChild(editor.ui.view.toolbar.element);
        })
        .catch(error => {
            console.error(error);
        });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalSeminar/OnlineGallery/Views/Product/Index.cshtml
@model IEnumerable<OnlineGallery.Models.Product>

@{
    ViewData["Title"] = "Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="text-center"><i class="fas fa-box-open"></i>&ensp;@ViewData["Title"]</h1>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

FinalSeminar/OnlineGallery/Views/Product/_ViewAll.cshtml
@using OnlineGallery.Data

@inject ApplicationDbContext context

@model IEnumerable<OnlineGallery.Models.Product>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table id="product" class="table table-bordered table-striped" style="table-layout: fixed;">
                    <thead>
                        <tr>
                            <th class="align-middle text-center">
                                @Html.DisplayNameFor(item => item.Name)
                            </th>
                            <th class="align-middle text-center">
                                Appearance
                            </th>
                            <th class="align-middle text-center">
                                @Html.DisplayNameFor(item => item.Description)
                            </th>
                            <th class="align-middle text-center">
                                @Html.DisplayNameFor(item => item.DefaultPrice)
                            </th>
                            <th class="align-middle text-center">
                                @Html.DisplayNameFor(item => item.Status)
                            </th>
                            <th>
                                <a onclick="showInPopup('@Url.Action("CreateOrUpdate", "Product", null, Context.Request.Scheme)', 'New Product')" class="btn btn-success btn-block"><i class="fas fa-plus"></i></a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Name <br />
                                    @if (item.Image != null)
                                    {
                                        <img src="~/images/@item.Image" width="300" height="200" />
                                    }
                                    else
                                    {
                                        <span class="text-danger font-weight-bolder">Please update image for this product</span>
                                    }
                                </td>
                                <td>
                                    <ul>
                                        <li><strong>Id:</strong> @item.Id</li>
                                        <li><strong>Condition:</strong> @item.Condition</li>
                                        <li><strong>Year:</strong> @item.Year</li>
                                        <li><strong>Fuel:</strong> @item.Fuel</li>
                                        <li><strong>Color:</strong> @item.Color</li>
                                        <li><strong>Mileage:</strong> @item.Mileage</li>
                                        <li><strong>Engine:</strong> @item.Engine</li>
                                        <li><strong>Transmission:</strong> @item.Transmission</li>
                                        <li><strong>Doors:</strong> @item.Doors</li>
                                    </ul>
                                </td>
                                <td>
                                    @if (item.Description != null)
                                    {
                                        if (item.Description.Length > 500)
                                        {
                                            var shortDescription = item.Description.Substring(0, 500);
                                            <span class="full-description d-none">@item.Description</span>
                                            <span class="short-description">@shortDescription...</span>
                                            <input class="btnDescription font-weight-bolder bg-transparent border-0" type="button" value="Expand" />
                                        }
                                        else
                                        {
                                            <span>@item.Description</span>
                                        }
                                    }
                                </td>
                                <td class="text-center">
                                    @item.DefaultPrice.Value.ToString("C")
                                </td>
                                <td class="text-center">
                                    @if (item.Status)
                                    {
                                        if (item.Auction != null)
                                        {
                                            <span class='font-weight-bolder text-success'>Currently being auctioned</span>
                                        }
                                        else
                                        {
                                            <span class='font-weight-bolder text-primary'>On sale</span>
                                        }
                                    }
                                    else
                                    {
                                        if (item.Image == null)
                                        {
                                            <span class='font-weight-bolder text-secondary'>Haven't updated image yet</span>
                                        }
                                        else if (!Tools.CheckGalleryProduct(context, item.Id))
                                        {
                                            <span class='font-weight-bolder text-warning'>Haven't updated gallery yet</span>
                                        }
                                        else
                                        {
                                            <span class='font-weight-bolder text-danger'>Sold</span>
                                        }
                                    }
                                </td>
                                <td class="text-center">
                                    @if (!Tools.IsSold(context, item.Id))
                                    {
                                        @if (item.Image != null)
                                        {
                                            if (item.Auction != null)
                                            {
                                                <a href="/Home/AuctionDetail/@item.Auction.Id" class="btn btn-dark">Go to Auction</a>
                                            }
                                            else
                                            {
                                                <a onclick="showInPopup('@Url.Action("CreateOrUpdate", "Product", new { item.Id }, Context.Request.Scheme)', 'Update Product')" class="btn btn-info">Edit</a>
                                                if (!Tools.CheckGalleryProduct(context, item.Id))
                                                {
                                                    <a onclick="showInPopup('@Url.Action("AddGallery", "ProductImage", new { item.Id }, Context.Request.Scheme)', 'New Gallery')" class="btn btn-warning">Create Gallery</a>
                                                }
                                                else
                                                {
                                                    <a onclick="showInPopup('@Url.Action("CreateAuction", "Auction", new { item.Id }, Context.Request.Scheme)', 'New Auction')" class="btn btn-primary">Create Auction</a>
                                                }
                                            }
                                        }
                                        else
                                        {
                                            <a onclick="showInPopup('@Url.Action("CreateOrUpdate", "Product", new { item.Id }, Context.Request.Scheme)', 'Update Product')" class="btn btn-info">Edit</a>
                                            <a onclick="showInPopup('@Url.Action("AddImage", "Product", new { item.Id }, Context.Request.Scheme)', 'Update Product')" class="btn btn-danger">Add Image</a>
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

<script>
    let btnList = document.getElementsByClassName('btnDescription');
    let shortList = document.getElementsByClassName('short-description');
    let fullList = document.getElementsByClassName('full-description');

    for (let i = 0; i < btnList.length; i++) {
        btnList[i].addEventListener('click', () => {
            if (btnList[i].value == "Expand") {
                btnList[i].value = "Collapse";
                shortList[i].classList.add('d-none');
                fullList[i].classList.remove('d-none');
            } else {
                btnList[i].value = "Expand";
                fullList[i].classList.add('d-none');
                shortList[i].classList.remove('d-none');
            }
        })
    }
</script>